### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by Uchiyu006** [Uchiyu006/review-reflect#20]
### 実装予定の機能

- [ ] ユーザー登録
- [ ] ログイン認証
- [ ] レビュー作成画面
- [ ] 作成したレビュー一覧
- [ ] 作成したレビュー詳細
- [ ] SNS投稿（シェアリンク）
- [ ] 作成したレビューの編集

### 必要なページ

- [ ] トップ
- [ ] ログイン
- [ ] ユーザー登録
- [ ] ユーザー設定
- [ ] お問い合わせ（フォーム）
- [ ] お問い合わせ（送信完了）
- [ ] プライバシーポリシー
- [ ] 利用規約
- [ ] パスワード再設定（メールアドレス入力）
- [ ] パスワード再設定（パスワード入力）
- [ ] レビュー作成
- [ ] レビューまとめ
- [ ] レビュー一覧
- [ ] レビュー詳細
- [ ] レビュー編集

**Comment by Tsuchiya2** [comment]
<img width="898" alt="image" src="https://github.com/Uchiyu006/review-reflect/assets/61481161/2b542e73-4f5e-4f2a-9320-16ef2c2f65fc">

projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認いただいて、上記が確認できる状態での提出をお願いいたします。

**Comment by Uchiyu006** [comment]
失礼いたしました。Projectを紐づけたのですが確認できますでしょうか？

**Comment by ippei-shimizu** [comment]
修正をしていただきありがとうございます。
以下、追加で気になった点をコメントさせていただきます。

--- 

レビュー作成ページ、レビューまとめページ、レビュー詳細ページ、レビュー一覧ページのissueですが、こちらのissueにはデザイン反映（HTML、CSS）を行うタスクも含まれていますでしょうか？
もし、デザイン反映タスクも含まれている場合でしたら、「レビュー周りの機能実装のissue」と「デザイン反映周りのissue」を分けて作成しておくと、issueを細かく分けることができ、ストーリポイントもさらに具体的に設定できると思います。

例）
- レビュー作成機能実装（レビューを作成する機能を実装するissue）
- レビュー作成ページ作成（デザインを反映させるissue）

**Comment by Uchiyu006** [comment]
アドバイスありがとうございます。
レビュー関係のページにつきましてissueを機能とデザインで分けました。
いかがでしょうか？

**Comment by tmtkzk0823** [comment]
いいと思います！
LGTMです！
